### ISSUE TITLE
Error Line 1

### ISSUE THREAD

**Issue by eric859** [grkblood13/m3u-builder#1]
![image](https://user-images.githubusercontent.com/29680516/28749842-c96fce84-74a2-11e7-8602-d62c1107109d.png)
As soon as I edit the source1.cfg and start the .js file, I get this error.

**Comment by grkblood13** [comment]
You don't appear to be using the nodejs command prompt as directly. The simplest way to install on Windows is to install Nodejs, open the Nodejs command prompt, and type "npm install m3u-builder -g". If you install that way you can run the program by simply typing "m3u-builder" from the normal windows command prompt or the nodejs one.

**Comment by eric859** [comment]
what dir structer should i use?

**Comment by grkblood13** [comment]
For me on Win10, everything goes to:
C:\Users\USERNAME\AppData\Roaming\npm\node_modules\m3u-builder

**Comment by eric859** [comment]
1. Here's what i did:
2. installed node .js 
3. opened a node command prompt
4. Ran the install line you mentions
5. It installed in C:\Users\Eric\AppData\Roaming\npm\node_modules\m3u-builder
6. I edited the source1.cfg file to add my .m3u and .xml 
7. From the node.js command prompt I cd's into the C:\Users\Eric\AppData\Roaming\npm\node_modules\m3u-builder directory and tried to run m3u-builder.js and I got the error shown in my previous message

**Comment by grkblood13** [comment]
If you want to, email your config file to grkblood13@hotmail.com and I'll take a look at it and tell you what's wrong.

**Comment by grkblood13** [comment]
FYI, you shouldnt have to go to any specific directory to run the program, just type 'm3u-builder'. When you install it via npm it resolves the paths for you.

**Comment by eric859** [comment]
I emailed them to you.  Thanks!

**Comment by eric859** [comment]
I've been trying to decifer the instructions and I think I see the issue.  I use a customized local file on my c: drive for the m3u and xmltv files.  Looks like you required a URL for the file location?  Can I use smb://...?

**Comment by grkblood13** [comment]
I emailed you back.

**Comment by grkblood13** [comment]
Just added support for local files.
