### ISSUE TITLE
Specify Channel number

### ISSUE THREAD

**Issue by usergood** [grkblood13/m3u-builder#14]
Any chance that you will implement setting  channel number based on channel names?
With that i mean this part:
"#EXTINF:-1 "  
To replace -1 for a specified number i would assign to certain channels.

Just to explain why i have this need is because i have started to use my tvheadend for Plex Live-tv as well, and it sure a pain to manually map all channel to a certain providers channel number to get plex to understand wich epg to use.

Since per default today every channel gets -1 then the just get assigned the channel numbers in ascending order, i think to just assign a specific number to a certain channel would be possible.

Thanks you for you great tool!
Keep up the good work!

**Comment by grkblood13** [comment]
So would the m3u file just be in order from 0? ie the first channel on the top of the list be EXTINF:0, followed by 1,2,3, etc. ?

**Comment by usergood** [comment]
Not exactly, since the numbering for my situationen isn't in direct order.
I have channels likes this:
Channelnumber and then channel-name
1 Channel 1,
2 Channel 2, 
3 Channel 3,
21 Channel 1 HD
22 Channel 2 HD,
23 Channel 3 HD

So my suggestion is to keep -1 as default channel number, then the client gives them the next free position from 1. (at least that is what tvheadend are doing).
And only assign channel numbers to thoose channels I directly specify in the configuration.
Because most channel providers has "gap" in their channel number order it will though to just giving them ascending order, so i think it will be easier to keep -1 for any unspecified channels.

Thanks for the quick answear.

**Comment by grkblood13** [comment]
I'm going to try to find some time this weekend to take a look at this.

**Comment by grkblood13** [comment]
I haven't forgotten about this. When I get to a stopping point with another project I'm working on I'll look at this. I don't think it'll be that hard to implement.

**Comment by grkblood13** [comment]
Capability has been added and push to baseline in version 2.2.0.
