### ISSUE TITLE
Status of your IPTV editor/features...

### ISSUE THREAD

**Issue by siliconhippy** [grkblood13/m3u-builder#17]
@gkrblood13,

After going through numerous online IPTV editors I decided to contact you as the expert: don't know how close you get to Perfect Player editor, but that is on Android and I feel comfy with Windows 7 (though I just hate Micro Serfers for it !)

So before I try out your stuff, I will make some tired old inquiries in hope of some recent updates...better ask you directly than those Kodi or Reddit warriors...

1. What I want.

- Simple Windows based IPTV editor that works with PVRs like Kodi Simple Client.

- Channel / group sorting (e.g., simple channel move up/down), selecting wanted channels and/or deletable channels. Import/exporting in m3u/8 format from online esp. pastebin URLs, or files on hard drive.

- EPG and xmltv info optional but not to be lost while editing !

- one pass testing and removal of non working) duplicate channels would be nice.

- possibly auto updates via say pastebin URLs. XStream costs and is probably overkill for individuals.

2. What I see.

- See this IPTV editor (Codeplex) update (by same author, from Readme):

http://www.tantrumtv.com/2017/09/08/tantrum-iptv-editor-released/

...and also here:

https://sourceforge.net/projects/vishutv/

- above summarizes my searches. 
So the first has good features- but the channel number sorting doesn't work, and no other sorting looks possible. Both versions mostly give random looking errors on files and URLs e.g. on even raw pastebin ones. The one pass testing and non working / duplicate link removal is OK and a good feature (no need for local VLC player.) You can edit channel, group, logo and EPG info too.

- The Vishu editor does select favorites channels, cannot sort based on channel number but you can move channels up and down in the list. However when transferring to the new select favorites file, you lose the logos !

3. So.

- what features from my wish list does your editor have? Do I need to include one EPG/ xmltv entry?

- any additional features?

- Don't see need for it, but did you include steiny59 attempt to do catch up TV?

- feel free to add comments.

Cheers,
Shippy.

**Comment by grkblood13** [comment]
If you're looking for a GUI-based editor then this isn't the tool for you. m3u-builder uses configuration files for all of it's sorting, which makes if more difficult than a GUI-based editor, but also makes it much more powerful with what it can do. I believe from a functionality standpoint it does everything other than verify whether or not a URL is valid. Keep in mind this is an editor, not a validation tool, which would be outside the scope of m3u-builders intent. Check out --interval under command line options for your question about auto updating. I haven't implemented the request from @steiny58 as it's not mergable in its current state. Perhaps I'll get around to it but I've been busy with other projects.
