### ISSUE TITLE
Ability to sort channel in order 

### ISSUE THREAD

**Issue by Adam2218** [grkblood13/m3u-builder#2]
I would love to be able to adjust the channel order. At the moment they are alphabetical

**Comment by grkblood13** [comment]
I'll try to get that done within the next week.

**Comment by Adam2218** [comment]
Wow, prompt response. cheers

**Comment by grkblood13** [comment]
Just pushed release v1.4.0 which features this capability. See 'setPosition' in the params.cfg section of the readme.
